services:
  postgres:
    image: postgres:17
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: apollo
      POSTGRES_PASSWORD: apollo
      POSTGRES_DB: apollo
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
