/* eslint-disable unicorn/prefer-string-replace-all */
// Merged from lockSession.cy.ts, navigateToFeature.cy.ts, transcriptSequence.cy.ts
// All three tests use the same large SM_V10_3 assembly, so it is loaded once in
// before() and shared across tests. lockSession modifies data so it runs last.
describe('Large assembly (SM_V10_3) tests', () => {
  before(() => {
    cy.loginAsGuest()
    cy.deleteAssemblies()
    cy.addAssemblyFromGff(
      'SM_V10_3.fasta.gff3.gz',
      'test_data/SM_V10_3.fasta.gff3.gz',
      false,
    )
  })

  beforeEach(() => {
    cy.loginAsGuest()
    cy.contains('Launch view', { timeout: 10_000 }).click()
  })

  after(() => {
    cy.deleteAssemblies()
  })

  it('Navigate to feature from table editor', () => {
    cy.selectAssemblyToView('SM_V10_3.fasta.gff3.gz', 'gene:Smp_313440')
    cy.annotationTrackAppearance('Show both graphical and table display')
    cy.contains('td', 'exon:Smp_313440.1.1').dblclick({ force: true })
    cy.currentLocationEquals('SM_V10_3', 192_138, 192_275, 50)

    cy.contains('td', 'exon:Smp_313440.1.13').dblclick({ force: true })
    cy.currentLocationEquals('SM_V10_3', 206_893, 207_445, 100)

    // Test refseq boundaries
    cy.searchFeatures('SM_V10_3:800..2000', 1)
    cy.contains('td', 'region1').dblclick({ force: true })
    cy.currentLocationEquals('SM_V10_3', 1, 1300, 100)

    cy.searchFeatures('SM_V10_3:498000..499100', 1)
    cy.contains('td', 'region2').dblclick({ force: true })
    cy.currentLocationEquals('SM_V10_3', 498_900, 500_000, 100)
    cy.contains('500,000')
  })

  it('Sequences from feature on reverse strand', () => {
    cy.selectAssemblyToView('SM_V10_3.fasta.gff3.gz', 'transcript:Smp_309950.1')
    cy.annotationTrackAppearance('Show both graphical and table display')
    cy.contains('transcript:Smp_309950.1', { timeout: 10_000 }).rightclick()
    cy.contains('Edit transcript details').click()
    cy.contains('Sequence').parent().parent().click()

    cy.get('[data-testid="sequenceOptionSelector"]').click()
    cy.get('[data-testid="sequenceOption-cDNA"]').click()
    // UTR
    cy.contains(
      'TAATACTAATAGGATTGTTtgtaatCCATAGCTAGGAATATATTATTGTTTGTCGGCGGC TTTTAACGCTTTGATACTTCTGTACCCTGTACGG',
    ).should('have.css', 'background-color', 'rgb(194, 106, 119)')

    // CDS start and end
    cy.contains(
      'ATGGAAATTGGGGACACAAGTGTAAA AGTTGGTGTTCGTGTTCGACCATTGTCAAGCAGTGAAGTGAATGATGGGAGTTCGACCTG TTTGTCATACCTAAATGAAGAAAATCAGCTAATAATTGGAAACGACAAGCTTTTTGGCTT',
    ).should('have.css', 'background-color', 'rgb(93, 168, 153)')
    cy.contains(
      'TCCTGCATCCATATCAGAAAGTAATGATAATGATGATTTACAATCTCCAACTAGCAATTC ACAACTATCTGATGGTGGGTCACTTCGTTATTTATGGCCTAAAAATCGCTTATCTTATTT TCCCAGTCCACTATTACGCTCAGACAGATAA',
    ).should('have.css', 'background-color', 'rgb(93, 168, 153)')

    // UTR
    cy.contains(
      'ATGTTTTCTAGCCCACAAAGATCTTCAAG AAATGTACTTCACTATCCTGGCTACGTTGGTTTCCTTTTCTTAGTTTAAAACACTTGTAC GTGGTTTCTGTGTGTGTATGTACGCTATCATTCTATCTCTTTTCACTTTTATCCAGTTTA TGTATATATTTGTTGCTTACAGTAGGACAAGTAGGATTATTTTAACTTGTGTGTTGTGTT TTGCTTCTTTATTTTTCACATTCCTAGTCCATTTCATTATGAATATTTTAGCTCCGATAT CCTGATTTGTTATTCATAAAATAATAAATACACTAAAACAAT',
    ).should('have.css', 'background-color', 'rgb(194, 106, 119)')

    cy.get('[data-testid="sequenceOptionSelector"]').click()
    cy.get('[data-testid="sequenceOption-CDS"]').click()
    cy.contains(
      `ATGGAAATTGGGGACACAAGTGTAAAAGTTGGTGTTCGTGTTCGACCATTGTCAAGCAGT
GAAGTGAATGATGGGAGTTCGACCTGTTTGTCATACCTAAATGAAGAAAATCAGCTAATA
ATTGGAAACGACAAGCTTTTTGGCTTTGACTATGTTTTCAAAGAAACAGATTCTCAAGAG
TATGTCTACAGAAAGGCTGCCCTTCCAATGGTTGAAAATATCCTCAAAGGATACAATGCT
ACTCTGTTTGCCTATGGTCAAACTGGAAGTGGGAAAACTTATACAATGGGTACATGTATC
TCCGAAAGTGTTATAGAAGGATCCGCTGGTATTGTTCCTCGAATTATTAAGGATTTATTT
GAGAAAATGCCAAATTATGAGTATGAATATACAGTGAAGGTTTCATTCCTGGAGATATAT
AAAGAGGATATACATGATCTGTTAGGCGAAGATGTATCTGCATCCCTACAAATACGAGAA
GAGAATCAACTTGTTAAGATTCCAGGCCTAACGGAAACAGTAGTCACATCTCCGGAAGAA
GTTCTTTATCTTCTTCACTGTGGTTCAACAAAAAGAAGTGTTGCGAGTACAGCGATGAAT
TTAAAATCCAGTCGCAGTCATGCCATTCTTACTCTATGTTTTCTGCTGCGGCCAAAGATA
ACACAGTTGGATGGGGAGAGTACAGAAGATACATTAACAGCTAAATTACATTTAGTCGAC
CTAGCTGGCTCTGAACGAATTAAGAAAACACATGCTGAAGGTGACCGACTTAAAGAAGGT
ATCGATATAAATAGAGGATTGCTGGCACTTGGTAATGTAATAAGTGCTTTATGCGAACGG
GACGCAAAGAAACGATCACATATTCCATATCGCGATTCACGTTTAACTCGCCTACTTCAA
GATTCGTTGGGCGGGAATAGTGCCACTTTAATGCTTGCTTGTGTTAGTCCTGCAGATATA
AATATGGAAGAGACATTGAACACACTTCGATATGCAGATCGAGCACGTTTAATTAAAAAT
AAACCAATTTTAAATCGTGCTGATCCTAAAGATGCTGAACTTGCTAAACTACGTGTTTTG
GTTGCTCAATTACAAGCACGATTAACTAATGGTTCTTCTTGTTTTCCACTACTCAGTCCT
TGTCCAAAAACAATTATTAAACCATTATCTGCTACTACTATTAATAACAATTCTACTAAC
AGTCAATTTTCTTCAGAATTAGTTACAAATCTTATGAATAAAAATAGAAAGTTAGAGAGT
GAGAAGCTTCTACTTTGTGCAGAATTAGATCAGACTGTCGAAAAAATGAATGAATTATAC
AGGAATAATTTCGATGCTGATAATTTACGTGATACAGTAATTTCGGAACTTCAAAAAGTT
GAATCAATTCTCAACTCCTTAAAACAGTTTGTTAGAGATAAATTCAATGAATCTCCTGAA
TTGATTAGTTATATTCAAGAATTGGAAGACATCCTAACTGGATTGATAAAAATTTTTAAT
GAGTCGAATAAAATTACGAATGAAGATTTAGAACATGCATATAAACAATCGTCTGATTTT
CTAGCTGAATTTCAATCAGACAGTACATGTTTCGATGCAGAAGAAGTAGTTGAAAAGACA
GCATTAAATATTCATACGGAAATCGACGTTAATAATAACGCTAACTGTATTTCAAATTTG
AGCAGTATTAAAACTACAGCGCAGCCGCAACTTGTTGATCGCTGGGGTTCTGAACTGCGC
GCACGTAGATTAGAATGTAAACAACGGATTGAGACAATTGAAGCTACTATACGTCAAAAG
AATGTTCTTCTAACTAGTTTAGAAGCTGCAGCTGAACAAGGAGATGAATCTTATTGTTTA
TTATTaaaaaaaTATGAATCTCAAATTCGTGAACTGGAATCAAAAGTTATTGATTTAGAG
CGCGAGAAATCCAAGCTGTTGGCAGAACACAGTAATGAAGAATTAAAAGATTCCAAAATG
CAACGAGAAGCACGTCTTAAGACTATGGAACAAGAATTAAATCAGACACGACGTCAACTA
ACTGAATTATCACGTTTAAAGAAAGCCAAAGAGGCTAGAGAAGCGGAATGTTTAAGATTG
AGAAACGAAATACAGTCGTTGAAATCTTCAATGATCCGATCAGCTAAACAATTGAAAGAA
GAAAGCACTGCTTATCGAAAATGGCGTAAAGAAAAGGAGACTGAGGTGAAAAAACTTCAA
GAGCATGATCGTCGGCTTCAGTGTGAAATGTCTCGTATGGTTTCAGTGCACGAACGACAA
CAAGCTGTACTAAAGCGTCGTATTGAAGCTGCTGCAGCTGCTGAACGTCGACTTAAAGAA
TTGTTATTACGTCAAAAAGATATTAGAAATGAACGTGATAAACGTGTATCTGAAGGAAAC
AATGCGAAAAAATTCGATTTGGCTACACGAGTTCGCGCTTGGGTCAAAACGGATTTAGAT
ATCCAAATCAGTATGGATGCTGTTAGATATCATTTGAGTCATTTTATGGATTCACGTAAA
ACTCTTTGTGATCGATTACGTACGATCGAAGCCAAAATGGAAAGTTGTCGACAAGATGGT
CAACCTTATGATATGTATATTGAAGAAGTGAACAGTCTTACTGAATCGATTCAATGTCAA
ACACAACAGATTAGCGATTTACAACAAAAACTTATGGATGCCGGTGAAAGATCATCGACA
GATGCTTCCGGCCCGCCTGATTCGACTGGTCAAATGCTTTCGTCTCGTTTGTCCCAACTA
CATAACATCCAAGAAGCACGAATAGCTTTGAAATATCTATTCAGACAAGCATCGTCATCT
GAAGTTTCTAAGATTAATTTGGAAACTCAAATAGACGAATTGGAATCTCAACTAAATGCA
GAGAAACAAAAAGTAGAAAATTTACTTCAGACTACAGAGCATTATTCTGTAGAATTACTG
AAATCTGAGGAGAATATGAAAGATATTCAATCTCGTCTTCAAGCTGCTAATGAACACATT
GATCAGTTAGAAAAAGAAAATGCTGAATTACGAGAAGCTTCGAAAATTCAACATGATAAT
TTAATGAAGATAAGATCATTGATGACAAATAGTTCATCTACTACTGGACTGACTGTCGAA
AATAAATTATCAAACACTCCAGTACTTCGTCAATATAGTAGTACTAATAATTGTACATTT
ACTTTGTTAAGTGATGATGAGAATGAGAATGTATATCCGCAAACAAATATTCCAACCGAT
AAATCACTGAACTTCACTGATGATTTAAACAACAATGATGGAGGCGAACCAGGAGTGAAG
TTGAAAAAAGTTGAAAGCGATTGGAGTTTATCATTTACGGTAGTCACTGATATTAATTCA
AACACTGATGCAGATTCACATCAACCTCGATGTAAATGCCGAAGAACATGTCAAGCACGG
TGTAGTTGTAAACGTTCCGGTCGTCCGTGTATTCCATCACATTGTCACTGTGTATTAGGT
CTATGCAAAAATCGTTCAGATTCATCATCGGAAAACAGTAAAATATTGAGTTCAGTCGAT
AATTCTGCAACTGTTATGGGACCACCATCTGGATTTCCTAAACGTAAAACTCGTGCATTA
CATTTAAATTTGAATAAAGAACAACAAAATGAACATGATGCTCATACAATGATGAATGAA
ACATACGATTTAAACAAACAACAGTCTCCTGCATCCATATCAGAAAGTAATGATAATGAT
GATTTACAATCTCCAACTAGCAATTCACAACTATCTGATGGTGGGTCACTTCGTTATTTA
TGGCCTAAAAATCGCTTATCTTATTTTCCCAGTCCACTATTACGCTCAGACAGATAA`.replace(/\n/g, ' '),
    )

    cy.get('[data-testid="sequenceOptionSelector"]').click()
    cy.get('[data-testid="sequenceOption-protein"]').click()
    cy.contains(
      `MEIGDTSVKVGVRVRPLSSSEVNDGSSTCLSYLNEENQLIIGNDKLFGFDYVFKETDSQE
YVYRKAALPMVENILKGYNATLFAYGQTGSGKTYTMGTCISESVIEGSAGIVPRIIKDLF
EKMPNYEYEYTVKVSFLEIYKEDIHDLLGEDVSASLQIREENQLVKIPGLTETVVTSPEE
VLYLLHCGSTKRSVASTAMNLKSSRSHAILTLCFLLRPKITQLDGESTEDTLTAKLHLVD
LAGSERIKKTHAEGDRLKEGIDINRGLLALGNVISALCERDAKKRSHIPYRDSRLTRLLQ
DSLGGNSATLMLACVSPADINMEETLNTLRYADRARLIKNKPILNRADPKDAELAKLRVL
VAQLQARLTNGSSCFPLLSPCPKTIIKPLSATTINNNSTNSQFSSELVTNLMNKNRKLES
EKLLLCAELDQTVEKMNELYRNNFDADNLRDTVISELQKVESILNSLKQFVRDKFNESPE
LISYIQELEDILTGLIKIFNESNKITNEDLEHAYKQSSDFLAEFQSDSTCFDAEEVVEKT
ALNIHTEIDVNNNANCISNLSSIKTTAQPQLVDRWGSELRARRLECKQRIETIEATIRQK
NVLLTSLEAAAEQGDESYCLLLKKYESQIRELESKVIDLEREKSKLLAEHSNEELKDSKM
QREARLKTMEQELNQTRRQLTELSRLKKAKEAREAECLRLRNEIQSLKSSMIRSAKQLKE
ESTAYRKWRKEKETEVKKLQEHDRRLQCEMSRMVSVHERQQAVLKRRIEAAAAAERRLKE
LLLRQKDIRNERDKRVSEGNNAKKFDLATRVRAWVKTDLDIQISMDAVRYHLSHFMDSRK
TLCDRLRTIEAKMESCRQDGQPYDMYIEEVNSLTESIQCQTQQISDLQQKLMDAGERSST
DASGPPDSTGQMLSSRLSQLHNIQEARIALKYLFRQASSSEVSKINLETQIDELESQLNA
EKQKVENLLQTTEHYSVELLKSEENMKDIQSRLQAANEHIDQLEKENAELREASKIQHDN
LMKIRSLMTNSSSTTGLTVENKLSNTPVLRQYSSTNNCTFTLLSDDENENVYPQTNIPTD
KSLNFTDDLNNNDGGEPGVKLKKVESDWSLSFTVVTDINSNTDADSHQPRCKCRRTCQAR
CSCKRSGRPCIPSHCHCVLGLCKNRSDSSSENSKILSSVDNSATVMGPPSGFPKRKTRAL
HLNLNKEQQNEHDAHTMMNETYDLNKQQSPASISESNDNDDLQSPTSNSQLSDGGSLRYL
WPKNRLSYFPSPLLRSDR*`.replace(/\n/g, ' '),
    )
  })

  // Runs last — modifies feature coordinates
  it('Lock session prevents editing', () => {
    cy.selectAssemblyToView('SM_V10_3.fasta.gff3.gz', 'gene:Smp_313440')
    cy.annotationTrackAppearance('Show both graphical and table display')
    cy.get('input[type="text"][value="192150"]')
      .first()
      .type('{selectall}{backspace}192140{enter}', {
        force: true,
      })
    // Refresh table editor
    cy.annotationTrackAppearance('Show graphical display')
    cy.annotationTrackAppearance('Show both graphical and table display')

    // Lock session
    cy.selectFromApolloMenu('Lock/Unlock session')
    cy.get('input[type="text"][value="192140"]')
      .first()
      .type('{selectall}{backspace}192130{enter}', {
        force: true,
      })
    cy.annotationTrackAppearance('Show graphical display')
    cy.annotationTrackAppearance('Show both graphical and table display')
    cy.contains('Cannot submit changes in locked mode')
    cy.contains('192140')
    cy.get('[data-testid="lock-icon"]').should('exist')

    // Unlock session
    cy.selectFromApolloMenu('Lock/Unlock session')
    cy.get('input[type="text"][value="192140"]')
      .first()
      .type('{selectall}{backspace}192130{enter}', {
        force: true,
      })
    cy.annotationTrackAppearance('Show graphical display')
    cy.annotationTrackAppearance('Show both graphical and table display')
    cy.contains('192130')
    cy.get('[data-testid="lock-icon"]').should('not.exist')
  })
})
